### ISSUE TITLE
Grid alignment issues using bsg_fakeram

### ISSUE THREAD

**Issue by tajayi** [bespoke-silicon-group/bsg_fakeram#4]
I was successfully able to use the generated macros in commercial tools, however I ran into some problems which needed to be worked around. The same work-arounds are not available or as easy using openroad tools.

1.  **Macro pins must be snapped to manufacturing grid**. The M4 pins should be snapped to the manufacturing grid (preferably metal routing tracks). For M4 on Nangate45, that would be a 0.28 pitch. Openroad is not yet smart enough to have dynamic routing grids.

2. **Bad orientation for M4 power stripes**. With Orientation R0, M4 power pins/stripes appear to be running horizontal. Not that M4 preferred direction for Nangate45 is vertical, and M5 horizontal. This means that if we wanted to do power routing for M5 to drop to M4, we would need to run M5 in a non-preferred direction which starts to cause other complications. It is probably recommended to have the signal pins on M3 or M2

3. **Snap macro size to width and height of placement tile** (H=1.4, W=0.19 for Nangate45). This may be an OpenROAD auto-placement issue. The tool ends up placing adjacent macros off the placement grid because of the way it gaps the cells. I can work around this in commercial tools by snapping the macros after placement, and will file an issue to the macro placement tool

**Comment by taylor-bsg** [comment]
Thanks Tutu!

**Comment by stdavids** [comment]
Hey Tutu,

I have pushed these features and should be available in the latest commit on master (8427274fe8bd847b1e6db5e3e4ff2cec46da4460). The config file has changed slightly -- mainly there are some new items and a couple have changed. Check out the new example cfg file, I believe this is what you will want for OpenROAD other than the specific SRAMs you need for your designs.

I'm not going to close this issue as there is quite a bit we are trying to enable here. Once you get a change to try it out let us know and we can address any additional issues or close out the issue.

**Comment by tajayi** [comment]
I'll give it another spin and provide feedback

**Comment by tajayi** [comment]
All good now.
